name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Going to directory
      #run: cd ./C && ls
    - name: Compile
      run: gcc ./main.c -o test.exe
    - name: Running
      run: ./executable
