name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Going to directory
      run: cd ./C && ls
    - name: installing gcc
      run: sudo apt-get install gcc
    - name: Compile
      run: gcc main.c -o executable
    - name: Running
      run: ./executable
